services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik:/etc/traefik
      - ./config/letsencrypt:/letsencrypt
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  traefik:
    name: traefik
    driver: bridge
